name: Docker Image CI

on:
    push:
        branches: ["releases"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build Docker Image
              run: |
                docker build ./terraform \
                --file Dockerfile \
                --tag ${{ github.repository }}:${{ github.ref_name }}